-- File uploads, in two halves that answer two different questions.
--
-- `submissions.files` is the answer: what the submitter actually attached, per field key. It
-- travels with the row, so reading the inbox or exporting a form never needs another lookup.
--
-- `file_uploads` is the ledger: what has been put in the bucket but not yet accounted for by a
-- submission. It exists so ingestion can tell "this key was really uploaded by this form" from
-- "this key is a string somebody made up", and so uploads that are never submitted can be found
-- again and deleted. Without it an abandoned upload would sit in the bucket forever, with no way
-- to tell it apart from one that is still waiting to be submitted.

ALTER TABLE submissions
    ADD COLUMN files JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE submissions
    ADD CONSTRAINT submissions_files_object_check CHECK (jsonb_typeof(files) = 'object');

CREATE TABLE file_uploads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    form_id UUID NOT NULL REFERENCES forms (id) ON DELETE CASCADE,
    -- The field this upload answers. Checked against the form's definition at upload time and
    -- again at ingestion, because the definition can change in between.
    field_key TEXT NOT NULL,
    -- Generated by this server, never by the client, which is what makes traversal impossible.
    object_key TEXT NOT NULL UNIQUE,
    -- As supplied, for showing the file back to a human. Never used to build a path.
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    -- Set when a submission claims this upload, and back to null when that submission is
    -- deleted. Null is therefore the only predicate the reaper needs: it covers both "uploaded
    -- and abandoned" and "its submission was removed".
    submission_id UUID REFERENCES submissions (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT file_uploads_size_check CHECK (size_bytes > 0)
);

-- The reaper's scan. Partial, because the table only ever grows while the unclaimed set stays
-- small.
CREATE INDEX file_uploads_unclaimed_idx ON file_uploads (created_at)
    WHERE submission_id IS NULL;

CREATE INDEX file_uploads_form_idx ON file_uploads (form_id, created_at DESC);
